[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings =["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/", "@solmate=/home/emmanuel/web3-file/foudry-web3/smart-contract-lottary-game/lib/solmate/src"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config/home/emmanuel/web3-file/foudry-web3/smart-contract-lottary-game/src

